# Assignment \#6: Asset Pricing

**Due:** Friday 29th April 2016 (by 6:00pm)

Please submit assignments to: 

> `econ370nyu@gmail.com` 

as a Jupyter notebook with your solutions.

In [1]:
%matplotlib inline
import numpy as np

#### Homework problems

** Question \#1 **

Please study the Python function in the following cell.  

Please assume that:

* $P$ is an $n \times n$ matrix of nonnegative numbers whose rows sum to 1

* $x$ is an $n \times 1$ vector

* $y$ is another $n \times 1$ vector

**a.** Please explain what the following things mean:

* $x * y$

* $P @ x$

* $cov$

**[Answer]**

**x * y**
This is an element-wise multiplication to produce a new $n \times 1$ vector with elements $x_1*y_1...x_n*y_n$.

**P@x**
This produces a new $n \times 1$ vector whose elements are linear combinations of the rows of P (considering each row to be $P_i$) with $x$, thus the new vector, let's call it $z = {P_1z, P_2z, ... P_n,z}$

**$cov$**
cov is the covariance, which is normally in the form of a positive semi-definite/definite matrix with the variances of the elements of a random vector along the diagonal and the covariances in the off diagonals.

**b.** Please propose some words in English telling what the function does

In [2]:
def covd(P,x,y):
    """
    
    """
    Ex = P @ x
    Ey = P @ y
    Exy = P @ (x*y)
    cov = Exy - Ex*Ey
    return cov

**[Answer]**

The function covd first instantiates two variables, $Ex$ and $Ey$, which correspond to a stochastic matrix $P$ multiplying a random vector, $x$ and $y$, respectively. This is the mathematical expectation of these random vectors. $Exy$ is then calculated, which is the mathematical expectation of the product of the two random vectors (broadcasted onto the elements and not the dot product). Then the function returns cov, a $n \times 1$ vector, which is contains the covariances between the elements of the $x$ and $y$ vectors for a given state. i.e. the $i$th element of cov is the covariance of $x_i$ and $y_i$ in state $i$.}}

-------------------------------------------------------------------------------------------------------------------

** Question \#2 **

In the next cell, we claim to generate a transition matrix 5 state Markov chain

In [3]:
def create_disaster_probability(diag=0.9, alpha=0.01, n=5):
    # Allocate for P
    offdiag = (1 - diag - alpha)/(n-2)
    P = np.ones((n, n)) * offdiag
    
    # Add to diag
    P = P + np.eye(5)*(diag-offdiag)
    
    # Update last column
    P[:, -1] = alpha
    
    # Last row
    P[-1, :] = np.zeros(n)
    P[-1, -1] = 0.5
    P[-1, n//2] = 0.5
    
    return P

P = create_disaster_probability(alpha=0.05)

**Please print out P and verify that it is a legitimate Markov transition matrix**

**[Answer]**

In [7]:
P

array([[ 0.9       ,  0.01666667,  0.01666667,  0.01666667,  0.05      ],
       [ 0.01666667,  0.9       ,  0.01666667,  0.01666667,  0.05      ],
       [ 0.01666667,  0.01666667,  0.9       ,  0.01666667,  0.05      ],
       [ 0.01666667,  0.01666667,  0.01666667,  0.9       ,  0.05      ],
       [ 0.        ,  0.        ,  0.5       ,  0.        ,  0.5       ]])

In [11]:
for row in P:
    if np.all(np.linalg.eigvals(P) > 0) != True:
        print("Not legitimate")
        break
print("legitimate")

legitimate


--------------------------------------------------------------------------------------------------------------------

**Question \#3**
 
 
A friend tells you that the price of an asset satisfies

$$ p_t = E_t m_{t+1} E_t (c_{t+1} + p_{t+1}) + cov_t (m_{t+1}, c_{t+1} + p_{t+1}) \quad (1) $$

where $p_t = v_t c_t$, $v_t$ is a function of the Markov state at $t$ and
 
* $E_t x_{t+1}$ is the conditional expectation of $x_{t+1}$
*  $m_t$ is a function of the Markov state 
*  $s_t$ is a function of the Markov state
* $P$ matrix is from Question \#2 
 
Three vectors m, v, and s are given by the successive rows of

* $m=[ 0.45351474,  0.4759072 ,  0.5       ,  0.52596976,  2.        ]$,
* $v =[ 1.11737826,  1.15554868,  1.19713735,  1.24262496,  2.09856868]$,
* $s =[ 1.05 ,  1.025,  1.   ,  0.975,  0.5  ]$
 
Please interpret these three vectors as random variables.  

Please verify that equation (1) holds with these values. (You'll have to write Python code to do this.)

**[Answer]**

$ p_t = E_t m_{t+1} E_t (c_{t+1} + p_{t+1}) + cov_t (m_{t+1}, c_{t+1} + p_{t+1})$

Recall $c_{t+1} = \lambda_{t+1} c_t$ and $p_t = v_t c_t$

$v_t c_t = E_t[m_{t+1}] E_t[c_{t+1} + p_{t+1}] + E_t[m_{t+1} \times (c_{t+1} + p_{t+1})] - E_t[m_{t+1}] E_t[c_{t+1} + p_{t+1}]$

$v_t c_t = E_t[m_{t+1}] E_t[\lambda_{t+1} c_{t} + v_{t+1} \lambda_{t+1} c_t] + E_t[m_{t+1} \times (\lambda_{t+1} c_{t} + v_{t+1} \lambda_{t+1} c_t)] - E_t[m_{t+1}] E_t[\lambda_{t+1} c_{t} + v_{t+1} \lambda_{t+1} c_t]$

Cancelling out all of the $c_t$ terms we get:

$v_t = E_t[m_{t+1}] E_t[\lambda_{t+1} + v_{t+1} \lambda_{t+1}] + E_t[m_{t+1} \times (\lambda_{t+1} + v_{t+1} \lambda_{t+1})] - E_t[m_{t+1}] E_t[\lambda_{t+1} + v_{t+1} \lambda_{t+1}]$

Simplifying a bit further we get:

$v_t = E_t[m_{t+1} \times (\lambda_{t+1} + v_{t+1} \lambda_{t+1})]$

Now to put this in a form where we can verify the given data in Python:

$v_i = \Sigma_{j=1}^n P_{ij} m_j (s_j + s_j v_j)$

Let $\hat{P}_{ij} = P_{ij}m_j$ 

Then: $v=\hat{P}s + \hat{P} s v$

In [77]:
m_t = np.array([0.45351474,0.4759072,0.5,0.52596976,2.])
v_t = np.array([1.11737826,1.15554868,1.19713735,1.24262496,2.09856868])
s_t = np.array([1.05,1.025,1.,0.975,0.5])

P_hat = P @ m_t 

#First solution (just turning the expectation into a formula)
P@(m_t * (s_t + s_t * v_t))

array([ 1.11737826,  1.15554868,  1.19713735,  1.24262497,  2.09856868])

-------------------------------------------------------------------------------------------------------------------

**Question \#4**

#### Returns

Returns are defined as $R_{t+1} = \frac{v_{t+1} + s_{t+1}}{v_t}$.

In our Markov setting, returns can be summarized by an $n \times n$ matrix whose $i,j$th component
is 

$$ R_{i,j} = \frac{(v_j s_j + s_j)}{v_i} $$

**Part A** Please create the matrix $R$ and verify

$$ 1 = E_t m_{t+1} E_t R_{t+1} + cov_t (m_{t+1}, R_{t+1}) $$

**[Answer]**

In [92]:
R = np.zeros((len(v_t),len(s_t)))

for i, item in enumerate(v_t):
    for j, item in enumerate(s_t):
        R[i][j] = (v_t[j]*s_t[j] + s_t[j])/v_t[i]

R

array([[ 1.98969969,  1.9773406 ,  1.96633265,  1.95686583,  1.38653525],
       [ 1.92397535,  1.91202451,  1.90138017,  1.89222607,  1.34073481],
       [ 1.85713625,  1.84560059,  1.83532604,  1.82648995,  1.29415755],
       [ 1.7891538 ,  1.77804041,  1.76814197,  1.75962934,  1.24678353],
       [ 1.0594112 ,  1.05283064,  1.04696948,  1.04192889,  0.73825763]])

$1 = E_t m_{t+1} E_t R_{t+1} + cov_t (m_{t+1} R_{t+1})$

$1 = E_t m_{t+1} E_t R_{t+1} + E_t (m_{t+1} R_{t+1}) - E_t m_{t+1} E_t R_{t+1}$

$1 = E_t (m_{t+1} R_{t+1})$

In [182]:
#Intuitively
print(P@(m * R[0]))
print(P@(m * R[1]))
print(P@(m * R[2]))
print(P@(m * R[3]))
print(P@(m * R[4]))

[ 1.          1.0341607   1.07138057  1.1120898   1.87811841]
[ 0.96696771  1.          1.03599041  1.07535493  1.81607985]
[ 0.93337516  0.96525991  1.          1.03799699  1.75298906]
[ 0.89920796  0.92992554  0.96339394  1.00000001  1.68881903]
[ 0.53244779  0.55063658  0.57045422  0.59212976  1.        ]


In [183]:
#Or more succinctly
m_tile = np.tile(m, (5,1))
P @ (m_tile * R).T

array([[ 1.        ,  0.96696771,  0.93337516,  0.89920796,  0.53244779],
       [ 1.0341607 ,  1.        ,  0.96525991,  0.92992554,  0.55063658],
       [ 1.07138057,  1.03599041,  1.        ,  0.96339394,  0.57045422],
       [ 1.1120898 ,  1.07535493,  1.03799699,  1.00000001,  0.59212976],
       [ 1.87811841,  1.81607985,  1.75298906,  1.68881903,  1.        ]])

What this means is that the mathematical expectation of the stochastic discount factor at a given Markov state and the vector of returns corresponding to that same Markov state is 1 (hence the 1's down the diagonal).

**Part B**

#### Possibly helpful or harmful hint

The following code is one person's attempt to answer this.
Do you think this code is correct?
If so can you do better?

Please explain

In [13]:
# Here is some code that implements the pseudo code R = (v*s + s)(tomorrow)/v(today)

v=np.array([ 1.11737826,  1.15554868,  1.19713735,  1.24262496,  2.09856868])
m=np.array([ 0.45351474,  0.4759072 ,  0.5       ,  0.52596976,  2.        ])
s=np.array([ 1.05 ,  1.025,  1.   ,  0.975,  0.5  ])

R1 = np.array((v*s + s)/v[0])
R2 = np.array((v*s + s)/v[1])
R3 = np.array((v*s + s)/v[2])
R4 = np.array((v*s + s)/v[3])
R5 = np.array((v*s + s)/v[4])

R = np.vstack([R1,R2,R3,R4,R5])
R

array([[ 1.98969969,  1.9773406 ,  1.96633265,  1.95686583,  1.38653525],
       [ 1.92397535,  1.91202451,  1.90138017,  1.89222607,  1.34073481],
       [ 1.85713625,  1.84560059,  1.83532604,  1.82648995,  1.29415755],
       [ 1.7891538 ,  1.77804041,  1.76814197,  1.75962934,  1.24678353],
       [ 1.0594112 ,  1.05283064,  1.04696948,  1.04192889,  0.73825763]])

**[Answer]**

I believe this code compiles correctly, but the actual code written is very inefficient. Because there is an iterative process of creating the rows of R dependent on entries of v, this can easily be put into a loop, as I have demonstrated below to more efficiently create the array, R.

In [21]:
for entry in v:
    try:
        np.append(R, (v*s+s)/entry)
    except:
        R = np.array(([(v*s+s)/entry]))
R

array([[ 1.98969969,  1.9773406 ,  1.96633265,  1.95686583,  1.38653525],
       [ 1.92397535,  1.91202451,  1.90138017,  1.89222607,  1.34073481],
       [ 1.85713625,  1.84560059,  1.83532604,  1.82648995,  1.29415755],
       [ 1.7891538 ,  1.77804041,  1.76814197,  1.75962934,  1.24678353],
       [ 1.0594112 ,  1.05283064,  1.04696948,  1.04192889,  0.73825763]])

**Part C**

An unnamed student in our class has said that she thinks the following code does
the same thing and is "better". Do you agree?  Can you please explain how this code works?


In [7]:
Rsf = np.reshape(v*s + s, (1, 5)) / np.reshape(v, (5, 1))
Rsf

array([[ 1.98969969,  1.9773406 ,  1.96633265,  1.95686583,  1.38653525],
       [ 1.92397535,  1.91202451,  1.90138017,  1.89222607,  1.34073481],
       [ 1.85713625,  1.84560059,  1.83532604,  1.82648995,  1.29415755],
       [ 1.7891538 ,  1.77804041,  1.76814197,  1.75962934,  1.24678353],
       [ 1.0594112 ,  1.05283064,  1.04696948,  1.04192889,  0.73825763]])

**[Answer]**

First of all the np.reshape($v*s+s$,(1,5)) is redundant because the operation $v*s+s$ already returns an array object that is of the shape (1,5). I agree that it is 'better' in the sense that it is more concise, but it is not as clear and so for didactic purposes, or even for the purposes of code-readability it suffers. I believe my code is nearly as concise, but is much more readable because the operations themselves are emphasized by the iterative process. 

Basically the code in Part C performs the operation $v*s+s$, and reshapes it (redundantly) to be of dimension (1,5). Then it performs row-wise division of elements, with perhaps some other things in the background for when the dimensions don't match, i.e. the code block below this answer. This makes things unclear to the reader exactly what is happening, and thus I don't think the code is necessarily better. 

In [35]:
test1 = np.array(([1,0]))
test2 = np.reshape(np.array(([2,1])),(2,1))

print(test1/test2)

[[ 0.5  0. ]
 [ 1.   0. ]]


In [33]:
test1 = np.array(([1,0],[1,1]))
test2 = np.reshape(np.array(([2,1])),(2,1))

print(test1/test2)

[[ 0.5  0. ]
 [ 1.   1. ]]


-------------------------------------------------------------------------------------------------------------------

**Question \#5**

Consider the problem in Question \#3

$$ p_t = E_t m_{t+1} E_t (c_{t+1} + p_{t+1}) + cov_t (m_{t+1}, c_{t+1} + p_{t+1}) \quad (1) $$

where $p_t = v_t c_t$, $v_t$ is a function of the Markov state at $t$ and
 
* $E_t x_{t+1}$ is the conditional expectation of $x_{t+1}$
*  $m_t$ is a function of the Markov state 
*  $s_t$ is a function of the Markov state
* $P$ is the same as in Question \#2
 

Suppose you only know P, m, and s:

* $m=[ 0.45351474,  0.4759072 ,  0.5       ,  0.52596976,  2.        ]$,
* $s =[ 1.05 ,  1.025,  1.   ,  0.975,  0.5  ]$
    
How do you compute the vector $v$ to satisfy the asset pricing function? 

[**Hint:** $v =[ 1.11737826,  1.15554868,  1.19713735,  1.24262496,  2.09856868]$]



**[Answer]**

I left off with v in this form.

---

$v_i = \Sigma_{j=1}^n P_{ij} m_j (s_j + s_j v_j)$

$v = Pms + Pmsv$

$v - Pmsv = Pms$

$v (I-Pms) = Pms$

$v = (I-Pms)^{-1} Pms$

---
So now we just need to isolate v.



In [135]:
np.linalg.inv(np.eye(5) - P*(m*s)) @ P@(m*s)

array([ 1.11737826,  1.15554869,  1.19713735,  1.24262497,  2.09856868])